# Generated by Django 5.0.6 on 2024-07-27 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_inventoryitem_created_at_alter_role_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ('-date',)},
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='created_at',
            new_name='date',
        ),
    ]
