# Generated by Django 5.0.6 on 2024-07-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_alter_inventoryitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='price',
            field=models.FloatField(),
        ),
    ]
